---
  - name: Get services running before update (centos7)
    shell: systemctl list-units --type service | grep running | awk '{print $1}'
    register: service_status_before
    changed_when: False
    args:
      warn: False

  - name: List running services
    debug:
      msg: "{{ service_status_before.stdout }}"
